-- List with all the resources
local resources = {
    { "VGshortcuts" },
	{ "MySQL" },
    { "VGmysql" },
	{ "VGtables" },
    { "VGcache" },
    { "VGscoreboard" },
    { "whitelist" },
    { "teams" },
    { "ipb" },
    { "runcode" },
    { "bone_attach" },
    { "VGcolorpicker" },
    { "customblips" },
    { "killmessages" },
    { "parachute" },
    { "particleobjects" },
    { "realdriveby" },
    { "reload" },
    { "superman" },
	{ "VGstats" },
	{ "VGinteriors" },
    { "VGdrawing" },
    { "VGmisc" },
    { "VGsettings" },
    { "VGuserdata" },
    { "VGutils" },
    { "VGpunish" },
    { "VGlogging" },
    { "VGaccounts" },
    { "VGblur" },
    { "VGchat" },
    { "VGdata" },
    { "VGplayers" },
    { "VGspawn" },
    { "VGcore" },
    { "VGweaponsync" },
	{ "VGpeds" },
	{ "VGjobscore" },
    { "VGblips" },
    { "VGadmin" },
    { "VGstaff" },
    { "VGdx" },
    { "VGhud" },
    { "VGmaps" },
    { "VGmods" },
    { "VGprogbar" },
    { "VGstream" },
    { "VGlaw" },
	{ "VGgetwanted" },
    { "VGpolicecomputer" },
    { "VGpolicemisc" },
    { "VGcruise" },
    { "VGfuel" },
    { "VGsirens" },
    { "VGpolicemisc" },
    { "VGvehiclemisc" },
    { "VGvehicles" },
    { "VGmodshop" },
    { "VGinventory" },
	{ "VGdrugs" },
    { "VGpaynspray" },
    { "VGphone" },
    { "VGtimer" },
    { "VGvip" },
    { "VGirc" },
    { "VGbases" },
    { "VGforum" },
    { "VGfoodstores" },
    { "VGplayerblips" },
	{ "DENmisc" },
    { "shaderBloom" },
    { "shaderCarpaint" },
    { "shaderContrast" },
    { "shaderDetail" },
    { "shaderRadialblur" },
    { "shaderRoadshine" },
    { "shaderWater" },
	{ "VGvehicleshops" },
	{ "VGjobvehicles" },
	{ "VGpsymisc" },
	{ "VGtaser" },
	{ "VGparamedic" },
	{ "VGinfopickups" },
	{ "VGbanking" },
	{ "VGdamage" },
	{ "VGfreecam" },
	{ "VGfisherman" },
	{ "VGjihad" },
	{ "VGpsymaps" },
	{ "VGtaxi" },
	{ "VGladder" },
}

-- When the resource starts
addEventHandler( "onResourceStart", resourceRoot,
	function ()
		for i = 1, #resources do
			if ( getResourceFromName( resources[ i ][ 1 ] ) ) and ( getResourceState ( getResourceFromName( resources[ i ][ 1 ] ) ) ~= "running" ) then
				startResource ( getResourceFromName( resources[ i ][ 1 ] ), true )
			end
		end
	end
)